#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jul 18 17:45:14 2019

@author: sandeep
"""

st = 'Print every word in this sentence that has an even number of letters'

for x in st.split():
    if len(x)%2 == 0:
        print(f"Even! -- {x}")
        