#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Thu Jul 18 17:46:04 2019

@author: sandeep
"""

for x in range(1,101):
    if x%3 == 0 and x%5 == 0:
        print(f"{x}-- FizzBuzz")
    elif x%3 == 0:
        print(f"{x}-- Fizz")
    elif x%5 == 0:
        print(f"{x}-- Buzz")
    else:
        print(x)